### ISSUE TITLE
Bridging issues

### ISSUE THREAD

**Issue by Ritzpink** [scroll-tech/contribute-to-scroll#108]
No fast trasactions while bridging

**Comment by a-rahman-g-a** [comment]
I believe the transactions on Scroll bridge need to be completed on faster basis, since it takes me now to withdraw from the new network (Scroll Sepolia) to Sepolia Ethereum more than one hour and that is considered long time comparing to a similar projects.

**Comment by dghelm** [comment]
Thanks for the feedback! Using the trustless bridge does take some time, and we're excited for 3rd party bridges to deploy to Scroll on mainnet, which will speed up the user experience for those who want to opt for speed over security. I'm unaware of which projects have a considerably faster native bridge though.

That said, this issue doesn't fit into the goals of this repo. Please join our Discord if you want to discuss more about our bridge.
