### ISSUE TITLE
Add Scroll to Eralend

### ISSUE THREAD

**Issue by GenRed77** [scroll-tech/contribute-to-scroll#109]
### Name of the project

Eralend

### Project type

Library

### Site of the project

https://eralend.com/

### Github repository of the project

https://github.com/eralend

### Networks

Scroll Mainnet

### Additional context

EraLend is designed to maximize the capital efficiency while minimizing the risks associated with the dependency on external liquidity & oracles. This will allow users to lend and borrow crypto assets more efficiently than any existing solutions in the market.

**Comment by isabellewei** [comment]
Hi @GenRed77  ! We'd be really excited about having Eralend on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
