### ISSUE TITLE
Add Scroll to Gains Network

### ISSUE THREAD

**Issue by anakalam999** [scroll-tech/contribute-to-scroll#112]
### Name of the project

Gains Network

### Project type

Library

### Site of the project

https://gainsnetwork.io/

### Github repository of the project

https://github.com/GainsNetwork

### Networks

Scroll Testnet - Sepolia

### Additional context

Gains Network is building the decentralized finance ecosystem of the future. Our goal is to build the most advanced and optimised suite of DeFi products in the space.

**Comment by isabellewei** [comment]
Hi @anakalam999 ! We'd be really excited about having Gains on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
