### ISSUE TITLE
Add multicall3 address for Scroll Sepolia to wagmi

### ISSUE THREAD

**Issue by RexCloud** [scroll-tech/contribute-to-scroll#114]
### Name of the project

wagmi

### Project type

Library

### Site of the project

https://wagmi.sh/

### Github repository of the project

https://github.com/wagmi-dev/viem

### Networks

Scroll Testnet - Sepolia

### Additional context

PR: https://github.com/wagmi-dev/references/pull/489

**Comment by RexCloud** [comment]
Edited the link to repository of the project since wagmi/chains was recently moved into viem
New PR: https://github.com/wagmi-dev/viem/pull/1112

**Comment by RexCloud** [comment]
Issue resolved!

![1](https://github.com/scroll-tech/contribute-to-scroll/assets/35985944/eae364a7-ac69-4a8e-9448-420471c48c93)

**Comment by dghelm** [comment]
Thanks for jumping on this one!
