### ISSUE TITLE
[Bridge] Infinite Claiming status if the transaction was rejected in Metamask

### ISSUE THREAD

**Issue by vadkutsen** [scroll-tech/contribute-to-scroll#115]
*Steps:*
1. As a user with some ETH on Scroll Sepolia start withdrawing from Scroll
2. Wait until the transaction is finalized and claiming is available
3. Click the Claim button
4. Reject the transaction in Metamask when offered
5. Observe the transaction status on the page

*Results:*
Claiming... status is shown infinitely. The user is unable to restart the claiming process

*Expected:*
The claiming process should be stopped. The Claim button should be shown to the user. The user should be able to restart the claiming process

![Screenshot 2023-09-02 at 00 33 42](https://github.com/scroll-tech/contribute-to-scroll/assets/20215056/1cecdbdb-d646-4431-9c58-1757e2e9160e)

**Comment by Queleaa** [comment]
Having the same issue. I think it's about network congestion.

**Comment by vadkutsen** [comment]
Closing this as @loveday suggested since the testnet problems should be reported in Discord
