### ISSUE TITLE
add scroll to the moon

### ISSUE THREAD

**Issue by abhisunnyak** [scroll-tech/contribute-to-scroll#1165]
### Name of the project

scroll

### Project type

Library

### Site of the project

scroll.com

### Github repository of the project

https://github.com/scroll-tech/contribute-to-scroll/issues/new?assignees=&labels=integration&projects=&template=add_scroll_to.yaml&title=Add+Scroll+to

### Networks

Scroll Mainnet

### Additional context

great project not like starknet

**Comment by NeonthunderX** [comment]
lmfao
