### ISSUE TITLE
Add Scroll to

### ISSUE THREAD

**Issue by zee01tukur** [scroll-tech/contribute-to-scroll#117]
### Name of the project

Wagami

### Project type

Library

### Site of the project

http://wagami.sh

### Github repository of the project

https://github.com/wagami-dev/wagami

### Networks

Scroll Testnet - Sepolia

### Additional context

Everything is going well for your work of this project

**Comment by dghelm** [comment]
This integration has already been made and this issue points to a non-existent repo and URL. Please avoid spam submissions.
