### ISSUE TITLE
Skunkworks Project Suggestion: Swap to $USDC

### ISSUE THREAD

**Issue by jchip300** [scroll-tech/contribute-to-scroll#121]
### Scoll linking to CEXes

Swapping to CEXes

### Project abstract

It would be really good for Scroll in the future if they were able to link to Coinbase or Crypto.com to help better fuel the network. Then so many more people could enjoy Scroll!

### Specification

It would be really good for Scroll in the future if they were able to link to Coinbase or Crypto.com to help better fuel the network. Then so many more people could enjoy Scroll!

**Comment by dghelm** [comment]
Not an OSS suggestion. Closing issue.
