### ISSUE TITLE
Add Scroll to BALANCER

### ISSUE THREAD

**Issue by Biloonov** [scroll-tech/contribute-to-scroll#123]
### Name of the project

Balancer - DeFi providing liquidity and automated portfolio management for cryptocurrencies.  It works as an automated portfolio manager and liquidity provider, allowing users to create and manage multi-token liquidity pools.  The balancer also includes a “smart order routing” mechanism that optimizes the trading process by dividing orders across multiple liquidity pools to achieve the best execution price.

### Project type

Library

### Site of the project

https://balancer.fi/

### Github repository of the project

https://github.com/balancer

### Networks

Scroll Mainnet

**Comment by dghelm** [comment]
Not a library, but an entire protocol. Not something that gets worked out in oss issues.

**Comment by Biloonov** [comment]
Thanks

сб, 14 окт. 2023 г., 00:45 Daniel Helm ***@***.***>:
