### ISSUE TITLE
Add Scroll to KINE PROTOCOL

### ISSUE THREAD

**Issue by Biloonov** [scroll-tech/contribute-to-scroll#124]
### Name of the project

Kine Protocol is a decentralized finance (DeFi) platform built on the Ethereum blockchain. It aims to provide decentralized lending and borrowing services for digital assets.

### Project type

Library

### Site of the project

https://www.kine.io/en-us

### Github repository of the project

https://github.com/Kine-Technology

### Networks

Scroll Mainnet

**Comment by dghelm** [comment]
Not a library, but an entire protocol. Not something that gets worked out in oss issues, but would be happy to see them deploy on Scroll.

**Comment by Biloonov** [comment]
Ok

сб, 14 окт. 2023 г., 00:46 Daniel Helm ***@***.***>:
