### ISSUE TITLE
Skunkworks Project Suggestion: Scroll Channel on Farcaster

### ISSUE THREAD

**Issue by NetWalker108** [scroll-tech/contribute-to-scroll#125]
### Name of the project

Scroll Channel on Farcaster

### Project abstract

The idea is to create a channel on Farcaster that is dedicated to all conversations and subjects about the Scroll ZKEVM system.

### Specification

Here is an example of a Farcaster channel: https://warpcast.com/~/channel/warpcast

Warpcast is channel that focuses on all conversations related to the Warpcast client.
<img width="616" alt="image" src="https://github.com/scroll-tech/contribute-to-scroll/assets/5716805/215daa8e-f857-489e-ba6e-f77bc4d97f07">

**Comment by pseudotheos** [comment]
Implemented.
