### ISSUE TITLE
Add Scroll to SushiSwap

### ISSUE THREAD

**Issue by Maksyaka12** [scroll-tech/contribute-to-scroll#24]
### Name of the project

SushiSwap

### Project type

Tool

### Site of the project

https://www.sushi.com/swap

### Github repository of the project

https://github.com/sushiswap

### Networks

Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @Maksyaka12 ! We'd be really excited about having SushiSwap on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
