### ISSUE TITLE
Scroll Mainnet in TOP dApps: Sushi, Balancer, Uniswap, 1inch etc.

### ISSUE THREAD

**Issue by Maksyaka12** [scroll-tech/contribute-to-scroll#26]
show Scroll Mainnet to the world :)

**Comment by Turupawn** [comment]
Hello @Maksyaka12 thanks for posting this issue! Uniswap and Sushi was already posted on #24 and #45 . So I'm going to close this issue. If you have a specific project that need such integrations or want to contribute on making the integration, feel free to post about it in the corresponding issues. For future issues please keep it to only one project per issue.
