### ISSUE TITLE
Add Scroll to Etherspot

### ISSUE THREAD

**Issue by gitsheel22** [scroll-tech/contribute-to-scroll#30]
### Name of the project

Etherspot

### Project type

Library

### Site of the project

https://etherspot.io/transactionkit/

### Github repository of the project

https://github.com/etherspot/

### Networks

Scroll Testnet - Sepolia

**Comment by isabellewei** [comment]
Hi @gitsheel22! We'd be really excited about having Etherspot on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
