### ISSUE TITLE
Suggestion to make Native Bridging more faster 

### ISSUE THREAD

**Issue by GelliacexCptl** [scroll-tech/contribute-to-scroll#32]
### Name of the project

Faster Transactions  like Native Bridging on Scroll

### Project abstract

It would be better if withdrawals / deposits made  from and to Scroll Mainnet to other networks is faster, everytime that I use it, it's always PENDING. The more faster it is, it will attract more users and also time effecient for everyone. 

### Specification

FASTER bridging tokens to and from another networks

**Comment by pajicf** [comment]
We kindly encourage you to utilize the Skunkworks board primarily for proposing new project ideas, while kindly reserving any bug or featuee reporting for alternative channels.
