### ISSUE TITLE
Add Scroll to HopProtocol

### ISSUE THREAD

**Issue by VasyaMono** [scroll-tech/contribute-to-scroll#34]
### Name of the project

HopProtocol

### Project type

Tool

### Site of the project

https://hop.exchange/

### Github repository of the project

https://github.com/hop-protocol/hop

### Networks

Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @VasyaMono ! We'd be really excited about having Hop Protocol on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
