### ISSUE TITLE
Add Scroll to DeBank

### ISSUE THREAD

**Issue by AndrMasliy** [scroll-tech/contribute-to-scroll#37]
### Name of the project

DeBank

### Project type

Tool

### Site of the project

https://debank.com/

### Github repository of the project

https://github.com/DeBankDeFi/

### Networks

Scroll Mainnet

### Additional context

Add Scroll Mainnet to DeBank for user`s comfortable

**Comment by isabellewei** [comment]
Hi @AndrMasliy! We'd be really excited about having DeBank on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)

**Comment by isabellewei** [comment]
Hi @sing1sing2 ! We'd be really excited about having Sismo on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
