### ISSUE TITLE
Skunkworks Project Suggestion:

### ISSUE THREAD

**Issue by sami1811** [scroll-tech/contribute-to-scroll#40]
### Name of the project

 Scroll's Official Testnet NFT Marketplace

### Project abstract

As an intermediate smart contract developer I found It difficult to deploy and test smart contract functionalities on third party NFT marketplaces as most of the time APIs are unresponsive or take lot of time to give a response. I think it would be a good idea for scroll team to come up with It's own NFT marketplace on scroll testnet. It might be easier to test NFT functionalities, other marketplaces support bunch of networks that makes them slow because of huge traffic from different networks. Scroll NFT market will only support Scroll testnets or maybe mainnet in future.

### Specification

Let's take https://zonic.app/ as an example. I'm using it at the moment but I have to wait for hours and sometimes days to get response of my function. Developers can make a simple and easy to interact user interface for testing purposes but I personally would like to see Scrolls official NFT marketplace on mainnet.

**Comment by pajicf** [comment]
Thank you for your submission to contribute-to-scroll.

While acknowledging the potential value and significance of your proposed project, Scroll team currently does not have any intentions of developing an official NFT marketplace application. 
However, we kindly encourage you to resubmit this issue with additional details regarding the product and match with someone from the community willing to further develop this application.
