### ISSUE TITLE
Add Scroll to Snapshot

### ISSUE THREAD

**Issue by MykolaMyr11** [scroll-tech/contribute-to-scroll#41]
### Name of the project

Snapshot

### Project type

Tool

### Site of the project

https://snapshot.org/

### Github repository of the project

https://github.com/snapshot-labs/snapshot

### Networks

Scroll Mainnet

### Additional context

Add Scroll to Snapshot for voting.
Comfortable decision for future Scroll.

**Comment by Giancarlo1969** [comment]
Integration

**Comment by isabellewei** [comment]
Hi @MykolaMyr11 ! We'd be really excited about having Snapshot on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
