### ISSUE TITLE
Skunkworks Project Suggestion: Scroll Fundation

### ISSUE THREAD

**Issue by FanMessi** [scroll-tech/contribute-to-scroll#43]
### Name of the project

Scroll Fundation

### Project abstract

Create Scroll Fundation: Twitter and Site.
This is space for all financial news about Scroll for understanding community.

### Specification

- news about: Scroll Native Token
- news about: Token Distribution
- news abot: New Partnerships (financial)
- etc.

**Comment by pajicf** [comment]
We appreciate your submission to contribute-to-scroll. 

However, Twitter profiles for Scroll and the Scroll community already exist. You can find them at the following locations: [Scroll_ZKP](https://twitter.com/Scroll_ZKP) and [BuildWithScroll](https://twitter.com/BuildWithScroll).
