### ISSUE TITLE
Add Scroll to uniswap

### ISSUE THREAD

**Issue by paul791** [scroll-tech/contribute-to-scroll#45]
### Name of the project

Uniswap

### Project type

Tool

### Site of the project

https://uniswap.org/

### Github repository of the project

https://github.com/Uniswap/

### Networks

Scroll Mainnet

### Additional context

uniswap is fast and cheaper,I think it's good choice to add it

**Comment by isabellewei** [comment]
Hi @paul791, thanks for the suggestion! We already have a governance proposal up for adding Uniswap to Scroll mainnet, please leave your comments there instead.
