### ISSUE TITLE
How to deploy a smart contract on Scroll. (Newbie's Guide)

### ISSUE THREAD

**Issue by cryptokidspark** [scroll-tech/contribute-to-scroll#492]
**First Step**: You need some Ethereum for gas on the scroll network. If you don't have Ethereum, bridge some using the [https://scroll.io/bridge](url)
**Second Step**: Add Scroll Network To Your Extension Browser using chainlist [https://chainlist.org/?search=SCROLL](url)
**Third Step**: Visit [https://remix.ethereum.org/](Remix) Next Click On Workspaces & Select Create, Then Set Template As Basic Or Default & New Workspace As Scroll Workspace Then Click "OK"
**Fourth Step**: Now Let’s Create A File, At The Top Left Click Create New File, Then Set Name For File, scroll.sol & Click Okay
**Fifth Step**: Now Proceed To Copy This Code Below & Paste In The File You Recently Created Then Click Okay

`pragma solidity 0.8.17;

// SPDX-License-Identifier: MIT

contract JEZFinance {
  string public name = "Jez Finance";
  string public symbol = "JEZ";
  uint8 public decimals = 18;
  uint256 public totalSupply = 10000000000;

  mapping (address => uint256) public balances;
  address public owner;

  constructor() {
    owner = msg.sender;
    balances[owner] = totalSupply;
  }

  function transfer(address recipient, uint256 amount) public {
    require(balances[msg.sender] >= amount, "Insufficient balance.");
    balances[msg.sender] -= amount;
    balances[recipient] += amount;
  }
}`

**Sixth Step**: Go To Solidity Compiler & Click Compile Scroll.sol
**Seventh Step**: Go To Deploy & Run Transactions, Then Select Injected Provider - MetaMask & Connect Your Wallet, Be Sure To Be On Scroll Mainnet,. Click Deploy & Confirm Transaction In MetaMask and wait for the transaction to be approved.

**There you go scroll fam you have deployed a contract on Scroll. If you come across this and you have problems while deploying the contract, please feel free to leave a comment for me and I will do well to respond to you as soon as possible.**

**Comment by cryptokidspark** [comment]
The links in the post do not work but here are the links
Official bridge: https://scroll.io/bridge
Chainlist: https://chainlist.org/?search=SCROLL

**Comment by pushprajj** [comment]
Looks fairly simple. Will give it a go later. Thanks.

**Comment by cryptokidspark** [comment]
> Looks fairly simple. Will give it a go later. Thanks.

Welcome mate, let me know if you need any help.
