### ISSUE TITLE
Add Scroll to Divvybet

### ISSUE THREAD

**Issue by Giancarlo1969** [scroll-tech/contribute-to-scroll#50]
### Name of the project

Divvybet

### Project type

Tool

### Site of the project

https://divvy.bet/

### Github repository of the project

https://github.com/metaplex-foundation/metaplex

### Networks

Scroll Mainnet

### Additional context

Add a DeFi sports betting platform on the Scroll Ecosystem.

**Comment by isabellewei** [comment]
Hi @Giancarlo1969  ! We'd be really excited about having a DeFi sports betting platform on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
