### ISSUE TITLE
Add Scroll to Jumper Exchange (Li.Fi) 

### ISSUE THREAD

**Issue by Semutireng22** [scroll-tech/contribute-to-scroll#51]
### Name of the project

Jumper Exchange (Li.Fi)

### Project type

Tool

### Site of the project

https://jumper.exchange/

### Github repository of the project

https://github.com/lifinance/jumper.exchange

### Networks

Scroll Mainnet

### Additional context

Hello Scroll Network,

I would like to recommend that you consider adding Scroll Mainnet to Jumper Exchange (Li.Fi). Li.Fi is a cross-chain bridge aggregation protocol that supports any-2-any swaps by aggregating bridges and connecting them to DEX aggregators.

By adding Scroll Mainnet to Jumper Exchange, you can provide broader access for users to exchange their cryptocurrencies in a fast, secure, and efficient manner. Li.Fi enables easy cross-chain asset exchanges by leveraging existing bridge networks.

Therefore, Scroll Mainnet users can seamlessly exchange their assets with a wide range of other cryptocurrencies available on Li.Fi. This will provide flexibility and convenience for users to diversify their portfolios and participate in a larger ecosystem.

I believe that integrating Scroll Mainnet into Jumper Exchange (Li.Fi) will bring significant benefits to Scroll Network and your users. By leveraging the features and advantages of the Li.Fi protocol, you can expand the reach and enhance the liquidity of Scroll Mainnet.

Thank you for considering this recommendation. I hope you will consider adding Scroll Mainnet to Jumper Exchange (Li.Fi) and enable more opportunities for your users.

**Comment by isabellewei** [comment]
Hi @Semutireng22! We'd be really excited about having Li.Fi on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
