### ISSUE TITLE
 Request for Dark Theme Support on  Website

### ISSUE THREAD

**Issue by AlexBusko** [scroll-tech/contribute-to-scroll#53]
Issue Description:
As an active user of scroll.io, I would like to request the implementation of a dark theme for the scroll.io website. Dark themes have become increasingly popular and sought after by users across various web platforms. The absence of a dark theme option on scroll.io limits the accessibility and user experience for individuals who prefer or require darker visual interfaces.

Benefits of a Dark Theme:

Enhanced Accessibility: Dark themes offer improved accessibility for users with visual impairments or sensitivity to bright light. The high contrast between dark backgrounds and light text can make it easier for individuals to read and interact with the content, ensuring a more inclusive experience.
Reduced Eye Strain: Many users spend prolonged periods on scroll.io, reading and engaging with content. A dark theme can significantly reduce eye strain by mitigating the contrast between the screen and the surrounding environment. This reduction in brightness helps prevent eye fatigue and allows users to comfortably browse and consume information for extended periods.
Aesthetic and Personalization: Dark themes have gained popularity due to their sleek and modern aesthetic appeal. By introducing a dark theme option, scroll.io would allow users to personalize their browsing experience and align it with their preferred visual style.
Consistency and Familiarity: Offering a dark theme would provide consistency across various platforms and applications that already support dark mode. Many users have grown accustomed to using dark themes across their digital tools, and having a consistent experience contributes to a more seamless workflow.

**Comment by Giancarlo1969** [comment]
Good idea mate. Well done !

**Comment by isabellewei** [comment]
Thanks for the suggestion! I've passed this feedback internally to our website team. Closing this issue as this isn't a task for open source contributors.
