### ISSUE TITLE
Add Scroll to Unstoppable Domains

### ISSUE THREAD

**Issue by ballpark711** [scroll-tech/contribute-to-scroll#54]
### Name of the project

Unstoppable Domains

### Project type

Tool

### Site of the project

https://unstoppabledomains.com/

### Github repository of the project

https://github.com/unstoppabledomains

### Networks

Scroll Mainnet

### Additional context

Bring the power of blockchain domains to the Scroll Network by partnering with Unstoppable Domains and having a custom extension for domains on Scroll (suggest .scroll)

**Comment by isabellewei** [comment]
Hi @ballpark711 ! We'd be really excited about having Scroll on Unstoppable Domains, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
