### ISSUE TITLE
Add scroll to pancakeswap

### ISSUE THREAD

**Issue by babulsahoo20** [scroll-tech/contribute-to-scroll#56]
### Name of the project

Pancakeswap

### Project type

Library

### Site of the project

https://pancakeswap.finance

### Github repository of the project

https://github.com/pancakeswap

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @babulsahoo20  ! We'd be really excited about having PancakeSwap on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
