### ISSUE TITLE
Add Scroll to Trust Wallet

### ISSUE THREAD

**Issue by Ghonghito** [scroll-tech/contribute-to-scroll#59]
### Name of the project

Trust Wallet

### Project type

Tool

### Site of the project

https://trustwallet.com/

### Github repository of the project

https://github.com/trustwallet

### Networks

Scroll Mainnet

### Additional context

A large number of users use Trust Wallet...

**Comment by isabellewei** [comment]
Hi @Ghonghito! We'd be really excited about having Trust Wallet integrated with Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
