### ISSUE TITLE
Skunkworks Project Suggestion: 

### ISSUE THREAD

**Issue by simp1ejackk** [scroll-tech/contribute-to-scroll#60]
### Name of the project

Direct Bridging

### Project abstract

There are tons of bridges that currently exist for most EVM chains. Therefore, theoretically a trader would likely be able to bridge their assets from Scroll to Ethereum, then Ethereum to X-Chain. However, this includes twice the number of steps that need to exist. There should, instead, be a bridge directly from Scroll to other chains, allowing traders to reduce the complexity, timing, and cost of converting their assets across different chains.

### Specification

Not sure what part of "specifications" I could provide, but I envision Hop's bridge when thinking about it. I think using a similar UI/UX would be pretty interesting.

**Comment by pajicf** [comment]
Thank you for your submission to contribute-to-scroll.

Although this does sound very valuable, it wouldn't be classified as Skunkworks project by this specification. It would be more of an integration request.
If you have some bridge in mind which you'd like to see on Scroll, then please use the ["Add Scroll to some tool or library"](https://github.com/scroll-tech/contribute-to-scroll/issues/new/choose) form
