### ISSUE TITLE
Add Scroll to Rainbow

### ISSUE THREAD

**Issue by Bekh-nam** [scroll-tech/contribute-to-scroll#63]
### Name of the project

Rainbow

### Project type

Library

### Site of the project

https://rainbow.me/

### Github repository of the project

https://github.com/rainbow-me

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @Bekh-nam ! We'd be really excited about having Scroll in Rainbow, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
