### ISSUE TITLE
Add Scroll to rhinofi

### ISSUE THREAD

**Issue by Liliatan** [scroll-tech/contribute-to-scroll#65]
### Name of the project

rhinofi

### Project type

Tool

### Site of the project

https://rhino.fi/

### Github repository of the project

https://github.com/rhinofi/

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

### Additional context

rhino.fi is opening DeFi to the entire world. People shouldn’t have to go through centralised web 3 exchanges to reach financial freedom – we believe they should have a gateway that takes them straight there.
they are  creating  gateway that allows you to enjoy the best of DeFi on any chain from a single wallet. We take niche blockchain technologies and make them universal, and we prioritise helping our users providing these new technologies to improve their lives over everything else.

**Comment by isabellewei** [comment]
Hi @Liliatan! We'd be really excited about having Sismo on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
