### ISSUE TITLE
Skunkworks Project Suggestion: Native crosschain EVM Token bridging

### ISSUE THREAD

**Issue by 0xsorcerers** [scroll-tech/contribute-to-scroll#67]
### Name of the project

EVM Token Bridge for Scroll

### Project abstract

My game to be deployed on Scroll can utilize any EVM Token to play, but what I find most helpful is having an already existing EVM token for like a standard ERC20 token on Ethereum or BNB chain but these are on external blockchains and usually require some sort of bridge to import, but what if we could do better? 

This will ultimately be safer without needing to use the dual liqudity approach or the oracle approach that can be gamed or taken advantage of

### Specification

Bridges are the weak link between blockchains, and outside chainlinks CCIP middleware, I believe Scroll create a Smart Bridge that can utilize a cross-chain message relayer and a simple custodian smart contract to ensure that every token on every blockchain can have a sister representation on Scroll if that contract token is sent to our custodian smart contract on that chain and lastly a custodian wallet on Scroll mainnet. The message relayer relays to the Scroll mainnet this contract from e.g Ethereum or BSC network has interacted with the custodian contract for so and so number of tokens or NFTs.
Our custodian wallet deploys a ties the caller contract address to a new contract deployed on Scroll and the contract mints the respective tokens for the caller for the msg.sender which would be the recipient. Whenever the msg.sender wants to retriever their tokens on the other end of the bridge (BSC or eth in this case), they can simply send their tokens to the Scroll custodian contract to be burnt and then the relayer relays to the external chain to release the withheld tokens from the custodian wallet to the msg.sender.

**Comment by pajicf** [comment]
Thank you for your submission to contribute-to-scroll.

While acknowledging the potential value and significance of your proposed project, Scroll team does not have intentions at the current moment of developing an official bridge to networks other than Ethereum.

What you've described sounds similar to our bridging architecture, but still applies only to Ethereum.
If you're interested, you can read more details in the [docs here](https://guide.scroll.io/developers/l1-and-l2-bridging).

I'll close this issue for now.
