### ISSUE TITLE
WE NEED MORE DAPPS WITH GREAT UI/UX ON SCROLL 

### ISSUE THREAD

**Issue by Cizzaro020197** [scroll-tech/contribute-to-scroll#683]
There are no much dapp on scroll mainnet yet with amazing UI/UX, i encourage the team to onboard more developers to the scroll ethereum layer 2 solution to build amazing dapps with great user experience and interface.... bringing more gamefi projects, real world asset dapps will onboard millions of users to web3 using scroll l2 as a funnel....

**Comment by Cizzaro020197** [comment]
MORE GAMEFI AND RWA DAPPS NEEDED ON SCROLL, ADOPT DEVELOPER INCENTIVES APPROACH SUCH AS GAS MONETIZATION PROGRAMS FOR DEVS AND DAPPS

**Comment by 0xReprezent** [comment]
that's hot.
