### ISSUE TITLE
Add Scroll to izumi

### ISSUE THREAD

**Issue by homayon1369** [scroll-tech/contribute-to-scroll#69]
### Name of the project

izumi

### Project type

Tool

### Site of the project

https://izumi.finance/

### Github repository of the project

https://github.com/IzumiFinance/

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @homayon1369  ! We'd be really excited about having Izumi on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
