### ISSUE TITLE
Add Scroll to LogX

### ISSUE THREAD

**Issue by jackylai87** [scroll-tech/contribute-to-scroll#703]
### Name of the project

LogX

### Project type

Library

### Site of the project

https://app.logx.trade/

### Github repository of the project

N/A

### Networks

Scroll Mainnet

### Additional context

Couldn't find any GitHub repositories from LogX but it would be nice if LogX could have Scroll integrated. With Twitter https://twitter.com/LogX_trade more than 157k followers and Discord more than 103k followers. It would be super nice to have Scroll in, this could really bring Scroll to reach wider audiences

**Comment by RoyKooiman** [comment]
Duplicate

For reference: https://github.com/scroll-tech/contribute-to-scroll/issues/352
