### ISSUE TITLE
Add Scroll to Locksmith Wallet

### ISSUE THREAD

**Issue by rjn-singh** [scroll-tech/contribute-to-scroll#72]
### Name of the project

Locksmith Wallet

### Project type

Tool

### Site of the project

https://www.locksmithwallet.com/

### Github repository of the project

https://github.com/scotthconner/smartrust

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

### Additional context

Locksmith is focusing on making wallet UX better and i would like to have them integrated to Scroll. 

David is excellent person leading BA side of locksmith and always looking for feedback on wallet ux improvement. 
https://twitter.com/David_Fols

**Comment by isabellewei** [comment]
Hi @rjn-singh ! We'd be really excited about having Locksmith on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
