### ISSUE TITLE
Add Scroll to Sismo

### ISSUE THREAD

**Issue by sing1sing2** [scroll-tech/contribute-to-scroll#73]
### Name of the project

Sismo

### Project type

Tool

### Site of the project

https://www.sismo.io/

### Github repository of the project

https://github.com/sismo-core

### Networks

Scroll Mainnet

### Additional context

identity but privacy preserving, prove things without exposing yourself to public.

**Comment by isabellewei** [comment]
Hi @sing1sing2 ! We'd be really excited about having Sismo on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
