### ISSUE TITLE
Add Scroll to Debank

### ISSUE THREAD

**Issue by Rouge3th** [scroll-tech/contribute-to-scroll#77]
### Name of the project

Debank

### Project type

Library

### Site of the project

https://debank.com/

### Github repository of the project

https://github.com/DeBankDeFi/

### Networks

Scroll Testnet - Sepolia

### Additional context

Add Scroll Mainnet to DeBank for user`s comfortable

**Comment by isabellewei** [comment]
Hi @Rouge3th ! We'd be really excited about having Debank on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
