### ISSUE TITLE
Add Scroll to Celer Network

### ISSUE THREAD

**Issue by Biloonov** [scroll-tech/contribute-to-scroll#79]
### Name of the project

Celer Network . Building the best inter-blockchain and cross-layer communication platform. 

### Project type

Tool

### Site of the project

https://cbridge.celer.network/

### Github repository of the project

https://github.com/celer-network

### Networks

Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @Biloonov! We'd be really excited about having Celer integrated with Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)

**Comment by Biloonov** [comment]
Great!

пт, 4 авг. 2023 г., 20:23 isabellewei ***@***.***>:
