### ISSUE TITLE
Add Scroll to Orbiter Finance

### ISSUE THREAD

**Issue by Biloonov** [scroll-tech/contribute-to-scroll#80]
### Name of the project

Orbiter Finance

### Project type

Tool

### Site of the project

https://www.orbiter.finance/

### Github repository of the project

https://github.com/Orbiter-Finance

### Networks

Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @Biloonov! We'd be really excited about having Orbiter on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)

**Comment by Biloonov** [comment]
Ok, thanks for the reply.

пт, 4 авг. 2023 г., 19:52 isabellewei ***@***.***>:
