### ISSUE TITLE
Add Scroll to owlto

### ISSUE THREAD

**Issue by EnergygitGit** [scroll-tech/contribute-to-scroll#85]
### Name of the project

owlto.finance

### Project type

Library

### Site of the project

https://owlto.finance/bridge

### Github repository of the project

https://github.com/owlto-finance/

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

### Additional context

https://owlto.finance/ Owlto Finance is a decentralized cross roll-up bridge focused on Layer 2.

**Comment by isabellewei** [comment]
Hi @EnergygitGit ! We'd be really excited about having Owlto on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
