### ISSUE TITLE
Add Scroll to Arkham tool

### ISSUE THREAD

**Issue by 0xhemubunny** [scroll-tech/contribute-to-scroll#86]
### Name of the project

arkham intelligence

### Project type

Tool

### Site of the project

https://www.arkhamintelligence.com/

### Github repository of the project

https://github.com/arkhamintelligence/

### Networks

Scroll Mainnet

### Additional context

For monitoring the transactions of address in the scroll mainnet would be good.

**Comment by isabellewei** [comment]
Hi @0xhemubunny ! We'd be really excited about having Arkham on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
