### ISSUE TITLE
Add Scroll to Rabby

### ISSUE THREAD

**Issue by Gamix115** [scroll-tech/contribute-to-scroll#87]
### Name of the project

Add Scroll to Rabby Wallet

### Project type

Tool

### Site of the project

https://rabby.io/

### Github repository of the project

https://github.com/RabbyHub

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

**Comment by isabellewei** [comment]
Hi @Gamix115 ! We'd be really excited about having Rabby on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
