### ISSUE TITLE
Add Scroll to ethereum-multicall

### ISSUE THREAD

**Issue by isabellewei** [scroll-tech/contribute-to-scroll#9]
https://github.com/joshstevens19/ethereum-multicall

**Comment by omahs** [comment]
Hey, just opened a PR here: https://github.com/joshstevens19/ethereum-multicall/pull/63

**Comment by Turupawn** [comment]
Hey @omahs thanks for your contributions! However there are a couple of things that are not correct. I detailed them on this review:
https://github.com/joshstevens19/ethereum-multicall/pull/63#pullrequestreview-1533883590

Do you want to do this corrections?

**Comment by omahs** [comment]
Hey @Turupawn sorry about this, I opened this new PR with the correction, could you please review it?
https://github.com/joshstevens19/ethereum-multicall/pull/65

**Comment by Turupawn** [comment]
@omahs Looks good! :clap: :clap: Please follow the Making a PR guide by editing the `contributions.json` file so we can give a poap
https://github.com/scroll-tech/contribute-to-scroll/blob/main/CONTRIBUTING.md#making-a-pr

**Comment by omahs** [comment]
@Turupawn Hey, great! I just made a PR there to add it

**Comment by RamanSB** [comment]
Hey @Turupawn shouldn't we mark this issue as closed?

**Comment by Turupawn** [comment]
Yes ty @RamanSB !
