### ISSUE TITLE
Add Scroll to Crust.Network

### ISSUE THREAD

**Issue by vivekbirana** [scroll-tech/contribute-to-scroll#91]
### Name of the project

Crust Network

### Project type

Library

### Site of the project

https://crust.network/

### Github repository of the project

https://github.com/crustio

### Networks

Scroll Testnet - Sepolia, Scroll Mainnet

### Additional context

Crust network provides cross chain data storage 
Crust network can be used to store dapps onchain permanently and at very cheap cost using simple API

**Comment by vivekbirana** [comment]
For more information, please refer to the EVM Storage Technical Light Paper:

https://ipfs.io/ipfs/QmSijA1yFvMxY2R6CxRzDNtrLA9h7v8hTxZqTvpgdSPsD3?filename=Crust+EVM+Storage.pdf

**Comment by isabellewei** [comment]
Hi @vivekbirana! We'd be really excited about having Crust on Scroll, however this work and decision-making process wouldn't be handled through open source repositories and isn't suited for this repo. Thanks for the suggestion :)
