### ISSUE TITLE
grammatical error

### ISSUE THREAD

**Issue by pucedoteth** [scroll-tech/contribute-to-scroll#92]
fix some grammatical error in Scroll Bridge Page.

**Comment by pucedoteth** [comment]
add screenshoot 
<img width="983" alt="Screenshot 2023-08-06 at 12 29 31 AM" src="https://github.com/scroll-tech/contribute-to-scroll/assets/119044801/4494fedd-f3d1-413f-aaa1-7cda3f42c4aa">

**Comment by pucedoteth** [comment]
@Turupawn could you see this

**Comment by dghelm** [comment]
Thanks for the report! We also have some outdated language from Goerli in there. Closing, as I've reported to the frontend team, and if you find anything else on the frontend, please consider submitting an issue to https://github.com/scroll-tech/frontends
