### ISSUE TITLE
Skunkworks Project Suggestion: 

### ISSUE THREAD

**Issue by FFicey** [scroll-tech/contribute-to-scroll#94]
### Name of the project

safety of funds and fraud prevention

### Project abstract

many frauds scams and other thievery relies on permissions initially given by the victim.

### Specification

When granting and signing acces to funds it would benfit users and slowdown criminals if not only a maximum amount but also a max date and or time could be specified by the end-user before signing or  confirming permission to access funds or NFTs.

**Comment by dghelm** [comment]
Interesting idea, but this seems like a diversion from Ethereum's behavior at the protocol level, which Scroll avoids in order to maintain developer experience. Specific applications might want to use something like this, but it might be better as an EIP.
