### ISSUE TITLE
Creating a Scroll book and a crowdin 

### ISSUE THREAD

**Issue by MathiasTELITSINE** [scroll-tech/contribute-to-scroll#95]
Hello everyone
A part often neglected on onboarding devs and new users is often a presentation of the project and all the associated content, translated in all languages.
I would like to propose that the Scroll team creates a Scroll book in this Git, where the technical specifities and ethos of Scroll would be explained, and the community would then translate it on Git.
Another solution for blog content for example would be to post it on Crowdin, one top tier platform for collaborative translation.

**Comment by isabellewei** [comment]
Hi! Our documentation is all public: https://github.com/scroll-tech/scroll-documentation

Feel free to add contributions or translations there.
